### ISSUE TITLE
抱歉，打扰一下您

### ISSUE THREAD

**Issue by ailunwowo** [Letian-stu/ESP32S3_Demo#1]
我有个问题想请教您一下，请问您写的这个语音识别是定制的唤醒词吗？

**Comment by Letian-stu** [comment]
不好意思没注意看，我是把menuconfig里的第一个COMMAND_ID0在自己的代码里设置唤醒了，你可以试试看，我记得有个define可以设置有唤醒和无唤醒

**Comment by ailunwowo** [comment]
无唤醒的话直接说命令就可以了吗？我看在vscode里看您的唤醒词是 da xian da xian 这个

**Comment by Letian-stu** [comment]
是的，你可以试试把#define CHANGE_WAKE屏蔽了，就可以不用唤醒词自己说命令了

**Comment by ailunwowo** [comment]
> 是的，你可以试试把#define CHANGE_WAKE屏蔽了，就可以不用唤醒词直接说命令了

我好像没搜索到这个 我只是把use wakenet给屏蔽了，但是并没有效果(我的板子是esp32s3box)

**Comment by ailunwowo** [comment]
> 是的，你可以试试把#define CHANGE_WAKE屏蔽了，就可以不用唤醒词直接说命令了

你是指的直接屏蔽调唤醒那一段代码吗？

**Comment by Letian-stu** [comment]
把这句屏蔽就行#define CHANGE_WAKE

**Comment by ailunwowo** [comment]
> 把这句屏蔽就行#define CHANGE_WAKE

我没找到这个横定义

**Comment by Letian-stu** [comment]
https://github.com/Letian-stu/ESP32S3_Demo/blob/ebbf459cea47b29c89155a6da0abf83605b8cf0b/speak_wakeup/main/app_speech_rec.c#L120
